CLASS zbp_i_cng_incidentn DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_cng_incidentn.
  PUBLIC SECTION.
    CONSTANTS c_status_pending  TYPE c LENGTH 10 VALUE 'PENDING'.
    CONSTANTS c_status_approved TYPE c LENGTH 10 VALUE 'APPROVED'.
    CONSTANTS c_status_rejected TYPE c LENGTH 10 VALUE 'REJECTED'.
ENDCLASS.



CLASS ZBP_I_CNG_INCIDENTN IMPLEMENTATION.
ENDCLASS.
